name: video_editor_repack
version: 3.0.2
description: |
 A flutter package for editing video with fully customizable UI.
 Supports crop, trim, rotation and cover selection.
 Provides commands to run in order to export the video or cover.
repository: https://github.com/lunigy/video_editor_repack

environment:
  flutter: ">=3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_flutter_minimal: ^6.0.4 # Updated to published package
  path: ^1.8.0 # update to `1.8.1` causes #79
  path_provider: ^2.0.12 # Needed for temp directory
  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  video_player: ^2.6.1
  # video_thumbnail: ^0.5.3 # Removed

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp

# No dependency overrides needed as we're using the published package